from __future__ import annotations
from app.features.learning.core import Question, Skill

SKILLS: dict[str, Skill] = {
    "variables": Skill(
        "variables",
        "Variables & types",
        "CS Foundations",
        "How programs store and name data.",
        "A variable is a named box holding a value; its type determines what you can do with it.",
        1,
    ),
    "conditionals": Skill(
        "conditionals",
        "Conditionals",
        "CS Foundations",
        "Making decisions in code with if/else.",
        "A conditional runs one branch of code depending on a boolean test.",
        2,
        ("variables",),
    ),
    "loops": Skill(
        "loops",
        "Loops",
        "CS Foundations",
        "Repeating work with for/while.",
        "A loop repeats a block; the loop variable changes each iteration, and the condition decides when to stop.",
        2,
        ("conditionals",),
    ),
    "functions": Skill(
        "functions",
        "Functions & abstraction",
        "CS Foundations",
        "Naming and reusing blocks of logic.",
        "A function packages a task: inputs in, output out; calling it runs the body with fresh local variables.",
        2,
        ("loops",),
    ),
    "lists_arrays": Skill(
        "lists_arrays",
        "Lists & arrays",
        "CS Foundations",
        "Ordered collections and indexing.",
        "A list holds items in order, accessible by index starting at 0; iteration visits each in turn.",
        3,
        ("loops",),
    ),
    "dicts_maps": Skill(
        "dicts_maps",
        "Dictionaries & maps",
        "CS Foundations",
        "Key→value lookups.",
        "A dictionary maps unique keys to values for fast lookup by key instead of position.",
        3,
        ("lists_arrays",),
    ),
    "big_o": Skill(
        "big_o",
        "Big-O & complexity",
        "CS Foundations",
        "How work grows with input size.",
        "Big-O describes worst-case growth: O(1), O(n), O(n log n), O(n^2). We care about the dominant term.",
        3,
        ("loops",),
    ),
    "sorting": Skill(
        "sorting",
        "Sorting algorithms",
        "CS Foundations",
        "Ordering data: bubble, merge, quick.",
        "Sorting arranges a collection; comparison sorts are O(n log n) at best, and merge sort guarantees it.",
        4,
        ("lists_arrays", "big_o"),
    ),
    "search_algos": Skill(
        "search_algos",
        "Search algorithms",
        "CS Foundations",
        "Finding items: linear vs binary search.",
        "Binary search halves a sorted range each step → O(log n); linear search is O(n) but works unsorted.",
        4,
        ("sorting",),
    ),
    "recursion": Skill(
        "recursion",
        "Recursion",
        "CS Foundations",
        "Functions that call themselves.",
        "Recursion solves a problem by solving smaller versions of itself; a base case stops the descent.",
        4,
        ("functions",),
    ),
    "stats_basics": Skill(
        "stats_basics",
        "Descriptive statistics",
        "AI & Data",
        "Mean, median, spread, and why they matter.",
        "Mean and median summarise the centre; variance/standard deviation measure spread; outliers distort the mean.",
        2,
        ("variables",),
    ),
    "regression": Skill(
        "regression",
        "Linear regression",
        "AI & Data",
        "Fitting a line to data.",
        "Linear regression finds weights and a bias minimising squared error between predictions and targets.",
        3,
        ("stats_basics", "functions"),
    ),
    "classification": Skill(
        "classification",
        "Classification & log loss",
        "AI & Data",
        "Predicting categories with probabilities.",
        "Classification predicts discrete classes; the model outputs probabilities, trained to minimise log loss.",
        3,
        ("regression",),
    ),
    "evaluation": Skill(
        "evaluation",
        "Model evaluation",
        "AI & Data",
        "Accuracy, precision/recall, ROC-AUC.",
        "Accuracy alone misleads with imbalanced classes; precision, recall and AUC measure the trade-offs.",
        4,
        ("classification",),
    ),
    "neural_networks": Skill(
        "neural_networks",
        "Neural networks intro",
        "AI & Data",
        "Layers, weights, activations.",
        "A network stacks layers of weighted sums with non-linear activations; depth lets it learn complex functions.",
        4,
        ("functions", "classification"),
    ),
    "training_loop": Skill(
        "training_loop",
        "Training & backpropagation",
        "AI & Data",
        "How networks learn from data.",
        "Backpropagation computes gradients of loss w.r.t. weights; gradient descent nudges weights downhill.",
        5,
        ("neural_networks", "regression"),
    ),
    "overfitting": Skill(
        "overfitting",
        "Overfitting & regularization",
        "AI & Data",
        "Memorising vs generalising.",
        "Overfitting learns train noise; regularization, more data, and early stopping improve generalisation.",
        4,
        ("evaluation", "training_loop"),
    ),
}

def questions_for(skill_id: str) -> list[Question]:
    return [q for q in QUESTION_BANK if q.skill_id == skill_id]

def question_by_id(question_id: str) -> Question | None:
    return next((q for q in QUESTION_BANK if q.question_id == question_id), None)

QUESTION_BANK: list[Question] = [
    Question(
        "q_var_1",
        "variables",
        "What does a variable named `score` store?",
        (
            "A named value of some type",
            "A fixed computation",
            "A file on disk",
            "A network address",
        ),
        0,
        1,
        "A variable binds a name to a value; the type of that value shapes what operations are valid.",
        "Variables are not files or fixed formulas — they're named slots for values.",
    ),
    Question(
        "q_var_2",
        "variables",
        'If you write `x = "5"` and `y = 2`, what is `x + y` in Python?',
        ("7", '"52"', "An error (type mismatch)", '"7"'),
        2,
        2,
        "Python won't add a string and an integer implicitly: str + int raises a TypeError.",
        "Type errors are common: the + operator means concatenation or addition depending on types.",
    ),
    Question(
        "q_var_3",
        "variables",
        "Which statement best describes a type?",
        (
            "It constrains what operations the value supports",
            "It is only used in machine code",
            "It changes every time the program runs",
            "It is the same as a variable name",
        ),
        0,
        1,
        "Types define the set of allowed operations (and storage), which lets tools catch mistakes early.",
        "Types aren't cosmetic — they define what's legal.",
    ),
    Question(
        "q_cond_1",
        "conditionals",
        "When is the `else` branch executed?",
        (
            "When the `if` condition is false",
            "Always",
            "When the `if` condition throws",
            "Never",
        ),
        0,
        1,
        "if/else is a fork: the if body runs when the test is true, else the else body runs.",
        "else is the fall-through, not an always-run block.",
    ),
    Question(
        "q_cond_2",
        "conditionals",
        "What does `if not logged_in: show_login()` do?",
        (
            "Show login when the user is NOT logged in",
            "Show login when the user IS logged in",
            "Always show login",
            "Never show login",
        ),
        0,
        2,
        "`not` negates the boolean, so the body runs only when logged_in is False.",
        "Negation flips the test — read `not` carefully.",
    ),
    Question(
        "q_cond_3",
        "conditionals",
        "Which is the correct order to check a grade: A(90+), B(80+)?",
        (
            "if score>=90: A; elif score>=80: B",
            "if score>=80: B; elif score>=90: A",
            "Check both with independent ifs first",
            "Order doesn't matter",
        ),
        0,
        2,
        "Order matters: once a branch matches, later branches are skipped; check the stricter condition first.",
        "Reversed order silently mis-grades 90–100 students as B.",
    ),
    Question(
        "q_loop_1",
        "loops",
        "How many times does `for i in range(3):` run?",
        ("3", "2", "4", "Infinite"),
        0,
        1,
        "range(3) yields 0,1,2 — three iterations.",
        "range(n) yields n values, starting at 0.",
    ),
    Question(
        "q_loop_2",
        "loops",
        "What's the sum after `total=0; for i in range(1,5): total += i`?",
        ("10", "15", "9", "5"),
        0,
        2,
        "range(1,5) = 1,2,3,4 → total 10. The upper bound is exclusive.",
        "Upper bounds in range are exclusive — the classic off-by-one.",
    ),
    Question(
        "q_loop_3",
        "loops",
        "Why does a `while True:` loop with no `break` hang?",
        (
            "The condition never becomes false",
            "The CPU is too slow",
            "The loop variable overflows",
            "None of these",
        ),
        0,
        1,
        "A loop must make progress toward a false condition or exit via break; otherwise it runs forever.",
        "Infinite loops are state bugs: something in the body must change the condition.",
    ),
    Question(
        "q_fn_1",
        "functions",
        "What is the return value of `def f(): 2 + 3` (no return)?",
        ("None", "5", "0", "An error"),
        0,
        1,
        "A function without an explicit return yields None.",
        "Not returning is not the same as returning 0 — you get None.",
    ),
    Question(
        "q_fn_2",
        "functions",
        "Why are functions useful?",
        (
            "They name and reuse logic, reducing duplication",
            "They make code run faster automatically",
            "They remove the need for variables",
            "They always return numbers",
        ),
        0,
        1,
        "Abstraction: define once, call many times; it also isolates bugs and documents intent.",
        "Functions are for organisation, not magic speed.",
    ),
    Question(
        "q_fn_3",
        "functions",
        "If `def add(a, b=2): return a+b`, what does `add(3)` return?",
        ("5", "3", "2", "Error — missing argument"),
        0,
        2,
        "b has a default of 2, so add(3) → 3+2=5.",
        "Defaults fill in missing arguments; they're not replaced.",
    ),
    Question(
        "q_list_1",
        "lists_arrays",
        'What is `items[0]` when `items=["a","b","c"]`?',
        ('"a"', '"b"', '"c"', "Error"),
        0,
        1,
        "Indexing starts at 0; the first element is items[0].",
        "Off-by-one: index 0 is the first element.",
    ),
    Question(
        "q_list_2",
        "lists_arrays",
        "What does `len([1,2,3])` return?",
        ("3", "2", "4", "The last element"),
        0,
        1,
        "len counts elements: three elements live in that list.",
        "len is a count, not an index — no off-by-one here.",
    ),
    Question(
        "q_list_3",
        "lists_arrays",
        "Why is appending to the end of a Python list O(1) amortised?",
        (
            "The list overallocates and usually has spare capacity",
            "Python is compiled",
            "Lists are actually arrays of pointers that never move",
            "Append is only O(1) for numbers",
        ),
        0,
        2,
        "Dynamic arrays reserve extra capacity, so append only occasionally triggers a grow-and-copy.",
        "Amortised ≠ always: occasional copies still exist, just rare.",
    ),
    Question(
        "q_dict_1",
        "dicts_maps",
        'What does `ages["ada"]` do in `ages = {"ada": 36}`?',
        ("Returns 36", 'Returns "ada"', "Deletes the entry", "Returns the key set"),
        0,
        1,
        "Dictionary lookup by key returns the mapped value.",
        "Keys map to values; the key itself isn't returned.",
    ),
    Question(
        "q_dict_2",
        "dicts_maps",
        "Which is the main advantage of a dict over a list for lookup?",
        (
            "Lookup by key is fast (≈O(1)) without scanning",
            "Dicts store values in order",
            "Dicts can hold more items",
            "Dicts are immutable",
        ),
        0,
        2,
        "Hash-based lookup avoids scanning every element; order and mutability aren't the point.",
        "The win is direct access by key — no linear scan.",
    ),
    Question(
        "q_dict_3",
        "dicts_maps",
        'What happens on `ages["bob"]` when "bob" is not a key?',
        ("KeyError", "None", "0", "An empty string"),
        0,
        1,
        "Plain subscript access raises KeyError for missing keys; .get() is the safe alternative.",
        "Missing-key access raises — use .get(key, default) when unsure.",
    ),
    Question(
        "q_bigO_1",
        "big_o",
        "What is the complexity of looking up an item in a hash map (average)?",
        ("O(1)", "O(n)", "O(log n)", "O(n log n)"),
        0,
        1,
        "Hash maps use direct bucket addressing; average case is constant time.",
        "Average O(1) — that's the whole point of hashing.",
    ),
    Question(
        "q_bigO_2",
        "big_o",
        "Which grows fastest as n increases?",
        ("O(n^2)", "O(n)", "O(n log n)", "O(log n)"),
        0,
        2,
        "Quadratic growth dominates: n² outruns n and n log n quickly.",
        "Order matters: log n < n < n log n < n².",
    ),
    Question(
        "q_bigO_3",
        "big_o",
        "Why do we ignore constant factors in Big-O?",
        (
            "We care about growth as input gets large, not the fixed overhead",
            "Constants are always zero",
            "Big-O is about output size",
            "We don't — constants always dominate",
        ),
        0,
        1,
        "Big-O abstracts the scaling behaviour; constants matter in practice but not asymptotically.",
        "Constant factors matter for real tuning — but not for complexity class.",
    ),
    Question(
        "q_sort_1",
        "sorting",
        "Which sort guarantees O(n log n) in the worst case?",
        ("Merge sort", "Bubble sort", "Insertion sort", "Selection sort"),
        0,
        2,
        "Merge sort always halves and merges: deterministic n log n. Bubble/insertion/selection are O(n²).",
        "Most simple sorts degrade to O(n²); merge sort doesn't.",
    ),
    Question(
        "q_sort_2",
        "sorting",
        "Why is quicksort O(n²) worst case but O(n log n) average?",
        (
            "Bad pivots can split the array very unevenly",
            "It sorts backwards",
            "It uses extra memory randomly",
            "Worst case is never observed",
        ),
        0,
        1,
        "Choosing the min/max as pivot repeatedly yields one-element partitions — quadratic.",
        "Pivot quality determines quicksort's fate; that's why random pivots help.",
    ),
    Question(
        "q_sort_3",
        "sorting",
        "What invariant does insertion sort maintain?",
        (
            "The prefix is sorted; each new element is placed into it",
            "The suffix is unsorted forever",
            "Every pair is swapped at most once",
            "The array is always fully sorted mid-run",
        ),
        0,
        1,
        "Insertion sort grows a sorted prefix left-to-right, inserting each next element in place.",
        "It's online-friendly: good for nearly-sorted data.",
    ),
    Question(
        "q_search_1",
        "search_algos",
        "What is binary search's time complexity?",
        ("O(log n)", "O(n)", "O(n log n)", "O(1)"),
        0,
        1,
        "Each step halves the range, so steps are log2(n).",
        "Halving gives logarithms — not linear time.",
    ),
    Question(
        "q_search_2",
        "search_algos",
        "What precondition does binary search require?",
        (
            "The data is sorted",
            "The data has no duplicates",
            "The data is small",
            "The data is in memory",
        ),
        0,
        1,
        "Binary search compares against the middle and must know which half to discard — requires sorted order.",
        "Ordering is the precondition; duplicates and size aren't disqualifiers.",
    ),
    Question(
        "q_search_3",
        "search_algos",
        "Linear search on 1,000,000 items: worst case comparisons?",
        ("1,000,000", "20", "500,000", "100"),
        0,
        2,
        "Linear search may check every element; binary search on the same sorted data needs ≈20.",
        "That difference is exactly why sorted data is worth maintaining.",
    ),
    Question(
        "q_rec_1",
        "recursion",
        "What stops infinite recursion?",
        (
            "A base case that returns without recursing",
            "Recursing twice",
            "Passing bigger inputs",
            "The interpreter",
        ),
        0,
        1,
        "Every valid recursion has at least one base case (no self-call) that terminates the descent.",
        "No base case = stack overflow.",
    ),
    Question(
        "q_rec_2",
        "recursion",
        "fact(n) = n * fact(n-1), fact(0)=1. What is fact(3)?",
        ("6", "3", "9", "12"),
        0,
        1,
        "3·fact(2)=3·2·fact(1)=3·2·1·fact(0)=6.",
        "Work the recursion down to the base case, then unwind.",
    ),
    Question(
        "q_rec_3",
        "recursion",
        "When is recursion a natural fit?",
        (
            "When the problem is defined in terms of smaller copies of itself",
            "Whenever you need speed",
            "Only for math problems",
            "Never",
        ),
        0,
        1,
        "Trees, divide-and-conquer, and nested structures are self-similar — recursion mirrors the definition.",
        "Speed isn't the criterion; structure is.",
    ),
    Question(
        "q_stats_1",
        "stats_basics",
        "Which statistic is most distorted by an extreme outlier?",
        ("The mean", "The median", "The mode", "None"),
        0,
        1,
        "The mean includes every value, so one huge value drags it; the median only depends on the middle.",
        "That's why house prices are reported as medians.",
    ),
    Question(
        "q_stats_2",
        "stats_basics",
        "A dataset has variance 0. What does that mean?",
        (
            "All values are identical",
            "Values are random",
            "The mean is 0",
            "It has one outlier",
        ),
        0,
        2,
        "Zero variance means no spread: every observation equals every other.",
        "Variance measures spread, not location.",
    ),
    Question(
        "q_stats_3",
        "stats_basics",
        "Mean=100, median=40, max=1000. What's the likely shape?",
        ("Right-skewed with outliers", "Symmetric", "Left-skewed", "Uniform"),
        0,
        1,
        "Mean >> median signals a long right tail of large values.",
        "Skew: mean chases the tail.",
    ),
    Question(
        "q_reg_1",
        "regression",
        "What does linear regression minimise?",
        (
            "Sum of squared errors",
            "Number of errors",
            "Data size",
            "Weight magnitudes only",
        ),
        0,
        1,
        "Least squares: the squared vertical distances between predictions and targets.",
        "Squared error punishes big misses and is differentiable — easy to optimise.",
    ),
    Question(
        "q_reg_2",
        "regression",
        "In y = w·x + b, what is b?",
        (
            "The intercept: predicted y when x=0",
            "The slope",
            "The error",
            "The learning rate",
        ),
        0,
        1,
        "b shifts the line vertically; w sets its steepness.",
        "Intercept vs slope — keep the roles straight.",
    ),
    Question(
        "q_reg_3",
        "regression",
        "What can a single linear model NOT fit?",
        ("A strongly curved relationship", "A straight line", "A constant", "A plane"),
        0,
        1,
        "A line can only express linear structure; curves need features or non-linear models.",
        "Linearity is the ceiling — hence features, polynomials, trees, nets.",
    ),
    Question(
        "q_cls_1",
        "classification",
        "A classifier outputs 0.9 for a spam email. What does 0.9 mean?",
        (
            "90% probability the model assigns to spam",
            "90% of emails are spam",
            "The model is 90% accurate overall",
            "There are 9 spam features",
        ),
        0,
        1,
        "It's the model's probability estimate for that instance — not an accuracy claim.",
        "Per-prediction probabilities ≠ global accuracy.",
    ),
    Question(
        "q_cls_2",
        "classification",
        "Which loss is standard for binary classification?",
        (
            "Log loss (binary cross-entropy)",
            "Squared error only",
            "Absolute error only",
            "Mean of labels",
        ),
        0,
        1,
        "Cross-entropy measures how far predicted probabilities are from true labels.",
        "Probabilities want log loss, not squared distance.",
    ),
    Question(
        "q_cls_3",
        "classification",
        'With class balance 99% negative, a model predicting "negative" always has accuracy ≈?',
        ("99%", "50%", "1%", "0%"),
        0,
        1,
        "Predicting the majority class yields accuracy equal to the majority share — yet it's useless.",
        "Accuracy without class balance is a trap — use precision/recall/AUC.",
    ),
    Question(
        "q_eval_1",
        "evaluation",
        "Precision measures…",
        (
            "Of predicted positives, how many were correct",
            "Of true positives, how many were found",
            "Overall correctness rate",
            "Model speed",
        ),
        0,
        1,
        "Precision = TP/(TP+FP): trustworthiness of a positive prediction.",
        "Precision vs recall is the classic trade-off (spam vs cancer screening).",
    ),
    Question(
        "q_eval_2",
        "evaluation",
        "Recall measures…",
        (
            "Of actual positives, how many were found",
            "Of predicted positives, how many were right",
            "The false positive rate",
            "Training time",
        ),
        0,
        1,
        "Recall = TP/(TP+FN): how many of the real positives we caught.",
        "Recall = catching the disease; precision = not alarming healthy people.",
    ),
    Question(
        "q_eval_3",
        "evaluation",
        "When is ROC-AUC a better headline metric than accuracy?",
        (
            "With imbalanced classes",
            "Only for regression",
            "When data is tiny",
            "AUC is always worse",
        ),
        0,
        1,
        "AUC is threshold-free and robust to imbalance; accuracy is not.",
        "AUC summarises ranking quality across thresholds.",
    ),
    Question(
        "q_nn_1",
        "neural_networks",
        "Why do neural nets need non-linear activations?",
        (
            "Stacked linear layers would collapse into one linear function",
            "To make weights bigger",
            "To reduce parameters",
            "They don't — they're optional",
        ),
        0,
        1,
        "Compositions of linear functions are linear; non-linearities let depth express complex functions.",
        "Without activation functions, a 200-layer net ≈ a single linear layer.",
    ),
    Question(
        "q_nn_2",
        "neural_networks",
        "What does a hidden layer compute?",
        (
            "A weighted sum of inputs followed by a non-linearity",
            "The final class label",
            "The loss value",
            "The gradient",
        ),
        0,
        1,
        "Each unit: z = Σ wᵢxᵢ + b, then a = activation(z).",
        "Layer math is always weight×input + bias, then activation.",
    ),
    Question(
        "q_nn_3",
        "neural_networks",
        'What does "depth" refer to?',
        ("The number of layers", "The number of weights", "Training time", "Data size"),
        0,
        1,
        "Depth = layers; width = units per layer. Both shape capacity.",
        "Depth isn't training time — it's architecture.",
    ),
    Question(
        "q_train_1",
        "training_loop",
        "What does backpropagation compute?",
        (
            "Gradients of the loss w.r.t. each weight",
            "The loss value itself",
            "The learning rate",
            "New data points",
        ),
        0,
        1,
        "Backprop applies the chain rule backward to get per-weight gradients efficiently.",
        "Backprop ≠ the loss; it's how we get the slope of the loss.",
    ),
    Question(
        "q_train_2",
        "training_loop",
        "Gradient descent updates weights by…",
        (
            "Subtracting the gradient times the learning rate",
            "Adding random noise",
            "Setting weights to zero",
            "Copying labels into weights",
        ),
        0,
        1,
        "w ← w − η·∇L moves opposite the gradient, downhill on the loss surface.",
        "Learning rate size controls step size; too big diverges, too small crawls.",
    ),
    Question(
        "q_train_3",
        "training_loop",
        "What does an epoch mean?",
        (
            "One full pass over the training data",
            "One training example",
            "One weight update",
            "One evaluation",
        ),
        0,
        1,
        "Epoch = complete sweep of the dataset; batches break it into steps.",
        "Epoch ≠ step: a step is one batch update.",
    ),
    Question(
        "q_of_1",
        "overfitting",
        "Which is the clearest sign of overfitting?",
        (
            "Training loss falls while validation loss rises",
            "Both losses fall together",
            "Both losses are high",
            "Validation loss is exactly 0",
        ),
        0,
        1,
        "The model is memorising the training set and losing generalisation — the classic divergence.",
        "The gap between train and validation curves is the tell.",
    ),
    Question(
        "q_of_2",
        "overfitting",
        "Which technique directly combats overfitting?",
        (
            "Regularization (e.g. weight penalty)",
            "Removing validation data",
            "Increasing model capacity",
            "Training longer",
        ),
        0,
        1,
        "Regularization constrains weights; more data, early stopping and dropout also help.",
        "More capacity or more training usually makes it worse.",
    ),
    Question(
        "q_of_3",
        "overfitting",
        "Why does early stopping help?",
        (
            "It halts training before validation error starts climbing",
            "It makes the optimizer faster",
            "It deletes data",
            "It freezes the architecture",
        ),
        0,
        1,
        "Checkpoints on validation error pick the model with best generalisation.",
        "Early stopping is a form of regularisation by model selection.",
    ),
]
